n_1 = int(input("Ingresa un numero"))
n_2 = int(input("Ingresa otro numero"))
suma = (n_1 + n_2)
resta = (n_1-n_2)
multiplicacion = (n_1*n_2)
division = (n_1/n_2)
print(suma)
print(resta)
print(multiplicacion)
print(division)
